name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Security Notice
        **Do NOT report security vulnerabilities here!**
        Email security@yourcompany.com instead.

  - type: dropdown
    id: implementation
    attributes:
      label: Implementation
      description: Which language implementation?
      options:
        - Java (Spring Boot)
        - Python (FastAPI)
        - Go
        - Rust
        - Infrastructure/Deployment
        - Documentation
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Impact severity
      options:
        - Critical (System down, data loss)
        - High (Major feature broken)
        - Medium (Feature partially broken)
        - Low (Minor issue, workaround exists)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear, concise description of the bug
      placeholder: When I..., the system...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce
      placeholder: |
        1. Configure...
        2. Execute API call...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System details
      value: |
        - OS: [e.g., RHEL 9.2]
        - SELinux: [enforcing/permissive/disabled]
        - Implementation Version: [e.g., Java 1.2.3]
        - Database: [PostgreSQL version]
        - JVM/Python/Go/Rust Version:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Application logs, audit logs, SELinux denials
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Screenshots, configs, related issues
